### ISSUE TITLE
contact setup 2

### ISSUE THREAD

**Issue by kevinheath** [baansconsulting/InsurPoint#33]
![contact setup 2](https://cloud.githubusercontent.com/assets/15248543/19071208/7fcef10e-89f4-11e6-9cad-fcf22c0ed0bb.png)

**Comment by baansconsulting** [comment]
You can now add SSN No and License number. User having access based on ROLE can only enter. We have given rights to user "baansconsulting@gmail.com" so that this user can eneter SSN and License number

**Comment by baansconsulting** [comment]
You can now add SSN No and License number. User having access based on ROLE can only enter. We have given rights to user "baansconsulting@gmail.com" so that this user can eneter SSN and License number

also state to hire  user cannot enter more information...its fixed

you can add cost center in Master area before setting up the client. Is this fine?

**Comment by kevinheath** [comment]
See other comment on this.
